# First Make File 

all: 
	@gcc demo.c -o myexe

run: 
	@./myexe ${name}

clean:
	@rm myexe

usage:
	@echo "*** use run target to execute the code ***"



#	Default Target : all

#	Target: Dependencies 
#	       Actions